owner: nerevar # Your GitHub username
repo: uptime_nerevar_com # Your GitHub repository name

sites: # List of endpoints to track
  - name: nerevar.com
    url: https://nerevar.com/
  - name: keen.nerevar.com
    url: https://keen.nerevar.com/

status-website:
  baseUrl: /uptime_nerevar_com # where "repo" is your repository name
  name: Nerevar websites monitoring
